import { syncPushToken } from "@/services/pushApi";
import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Device from "expo-device";
import * as Notifications from "expo-notifications";
import { useCallback, useEffect, useRef, useState } from "react";
import { Alert, Platform } from "react-native";

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldPlaySound: true,
    shouldSetBadge: true,
    shouldShowBanner: true,
    shouldShowList: true,
    priority: Notifications.AndroidNotificationPriority.MAX,
  }),
});

export const usePushNotifications = (userId?: number | string | null) => {
  const [fcmToken, setFcmToken] = useState<string | null>(null);

  const lastSyncedTokenRef = useRef<string | null>(null);

  const syncToken = useCallback(
    async (token: string) => {
      // If we already synced this exact token string, abort immediately
      if (!userId || lastSyncedTokenRef.current === token) return;

      const pushEnabled = await AsyncStorage.getItem("pushEnabled");
      if (pushEnabled !== "false") {
        lastSyncedTokenRef.current = token; // Cache it so we don't send it again
        await syncPushToken(userId, token);
      }
    },
    [userId],
  );

  const initializePush = useCallback(async () => {
    const token = await registerForPushNotificationsAsync();
    if (token) {
      setFcmToken(token);
      await syncToken(token);
    }
    return token;
  }, [userId]);

  useEffect(() => {
    if (!userId) return;

    // Listen for FCM token rotations generated by Google Play Services
    const tokenListener = Notifications.addPushTokenListener(
      async (newToken) => {
        setFcmToken(newToken.data);
        await syncToken(newToken.data);
      },
    );

    // Handle user interaction when tapping on a notification banner
    const responseListener =
      Notifications.addNotificationResponseReceivedListener((response) => {
        console.log(
          "User tapped notification payload:",
          response.notification.request.content.data,
        );
      });

    return () => {
      tokenListener.remove();
      responseListener.remove();
    };
  }, [userId, syncToken]);

  return { fcmToken, initializePush };
};

export async function registerForPushNotificationsAsync(): Promise<
  string | null
> {
  if (!Device.isDevice) {
    Alert.alert("Error", "Must use a physical device for Push Notifications");
    return null;
  }

  if (Platform.OS === "android") {
    await Promise.all([
      // Channel 1: Critical Alerts (Custom sound from app bundle)
      Notifications.setNotificationChannelAsync("alerts_critical", {
        name: "Critical Alerts",
        importance: Notifications.AndroidImportance.MAX,
        sound: "notifications_sound.wav",
        vibrationPattern: [0, 250, 250, 250],
        lightColor: "#FF231F7C",
      }),

      // Channel 2: Operational / Transactional (System default sound)
      Notifications.setNotificationChannelAsync("updates_operational", {
        name: "Order & Account Updates",
        importance: Notifications.AndroidImportance.HIGH,
        vibrationPattern: [0, 250],
      }),

      // Channel 3: Marketing / Promotional (System default sound)
      Notifications.setNotificationChannelAsync("marketing_promotional", {
        name: "Promotions & News",
        importance: Notifications.AndroidImportance.DEFAULT,
      }),
    ]);
  }

  const { status: existingStatus } = await Notifications.getPermissionsAsync();
  let finalStatus = existingStatus;

  if (existingStatus !== "granted") {
    const { status } = await Notifications.requestPermissionsAsync();
    finalStatus = status;
  }

  if (finalStatus !== "granted") {
    Alert.alert(
      "Permission Denied",
      "Failed to get push token for push notifications!",
    );
    return null;
  }

  try {
    const tokenData = await Notifications.getDevicePushTokenAsync();
    return tokenData.data;
  } catch (error) {
    console.error("Token Fetch Error:", error);
    return null;
  }
}
